package com.floorplan.maven.classes;

public enum ElementType {
    WALL, DOOR, WINDOW, FURNITURE, DELETE, CIRCLE, SMALL_WALL, MEDIUM_WALL, LARGE_WALL, VERTICAL_SMALL_WALL, VERTICAL_MEDIUM_WALL, VERTICAL_LARGE_WALL, SELECTOR, TRIANGLE // Added SELECTOR for the selection tool

}
