package com.floorplan.maven.classes;

public enum ElementType {
    WALL, DOOR, WINDOW, FURNITURE, DELETE, CIRCLE, SMALL_WALL, MEDIUM_WALL, LARGE_WALL,
    VERTICAL_SMALL_WALL, VERTICAL_MEDIUM_WALL, VERTICAL_LARGE_WALL, MOVE, TRIANGLE, ROTATE, RESIZE, 
    SELECT, RECTANGLE, COUCH, TABLE, BED, TOILET, BATHTUB, SINK, STOVE, SHOWER, FRIDGE, OPENING, VERTICAL_OPENING, OPENING_CUSTOM, ROOM, LINE, DOORREVERSE // Added SELECTOR for the selection tool

}
